### ISSUE TITLE
Slow slow file open after git checkout

### ISSUE THREAD

**Issue by lbradstreet** [tpope/vim-leiningen#8]
Hi Tim,

As you may remember, I love vim-fireplace (Clojurescript support etc). For a while now I've been experiencing bad delays opening up clj files. I've finally tracked this down to the following scenarios. 

1. Use vim-leiningen and vim-fireplace
2. Open vim
3. Checkout files via git checkout
4. Open a file. There will always be a multi second delay regardless of whether the file content changed. 

You can repeat the git checkout / file open process ad nauseum. 

Anyway, thanks again for vim-fireplace. Since I've disabled vim-lein my life is infinitely happier. I'm sure it all has something to do with modified times. 

Cheers

Lucas

**Comment by tpope** [comment]
Only modification time that should matter is `project.clj`. Is that file changing?

**Comment by lbradstreet** [comment]
OK, I think you're right, it's only when project.clj gets modified as part of a checkout. This happens pretty often changing branches and such so I thought it was from other files. Sorry for the false alarm.

Is the slowness intrinsic, or could I do some profiling and improve it? I'm quite happy with just vim-fireplace without vim-leiningen, so I'm not too worried.

**Comment by tpope** [comment]
If you bounce the REPL (which technically you should, since you need to do that after `project.clj` changes), it will use that to retrieve the classpath instead, avoiding the delay.

**Comment by lbradstreet** [comment]
Thanks for the info. I guess you're correct about bouncing the repl, but I don't always work that way (sometimes checkout a few times without actually doing anything but look at files). Much appreciated.
